openapi: 3.0.0
info:
  title: 'Igronik-lk API'
  version: '1.0'
paths:
  /api/newsList/:
    get:
      tags:
        - news
      summary: 'Get a list of news'
      description: 'Get a list of news'
      operationId: read
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
  '/api/news/{newsID}':
    get:
      tags:
        - news
      description: 'Get news by id'
      operationId: getSpecificNews
      parameters:
        -
          name: newsId
          in: path
          description: 'ID of news that needs to be fetched'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'successful operation'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/News'
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: 'News not found'
